name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create App
        run: |
          cordova create myapp com.example.time TimeApp
          cd myapp
          cordova platform add android
          # Очищаем стандартный контент и кладем ваш HTML
          rm -rf www/*
          cp ../index.html www/index.html
          # Важный костыль для стабильности сборки
          echo "sdk.dir=$ANDROID_SDK_ROOT" > platforms/android/local.properties
          cordova build android --debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: TimeConverter-APK
          path: myapp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
