name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Web to APK
        run: |
          echo "Сервер GitHub получил ваш HTML и готовит файл..."
